apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kingd4jensvc
  name: kingd4jensvc
  namespace: kube-king
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    x: kingjenkins
  type: NodePort
status:
  loadBalancer: {}

---  
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kingd4jenpod
    x: kingjenkins
  name: kingd4jenpod
  namespace: kube-king
spec:
  containers:
  - image: kingshuk10/kingd4webapp1:v1
    name: kingd4jenpod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
